#' Generate model simulation using gillespie algorithm
#'
#' Work in progress. fix list2env.
#'
#' @param listmodel named list generated by compilemodel
#' @param params named list of parameter values
#' @param x0 named list specifying initial (integer)
#' populations
#' @param tvec optional simulation time.
#' default is NA which specfies running until
#' process rates are zero
#' @param maxtransitions optionally limit total
#' number of population changes
#' default is NA which specfies running
#' until process rates are zero
#' @return tibble of dynamics with column t and
#' columns of state names
#' @export
#' @importFrom rlang .data
gillespie <- function(listmodel,
                      params,
                      x0,
                      tvec = NA,
                      maxtransitions = NA) {
  if (!is.list(listmodel)) {
    stop("input model must be named list with names
    processrates,updatedstates, and petermatrix), as generated by compilemodel")
  }
  if (!all(c(
    "processrates", "updatedstates",
    "petermatrix"
  ) %in% names(listmodel))) {
    stop("input model must contain names processrates,
    updatedstates, and petermatrix, as generated by compilemodel")
  }
  if (!is.na(tvec)) {
    maxt <- max(t)
  } else {
    maxt <- Inf
  }

  strprocesses <- listmodel$processrates
  # load parameters as variables
  list2env(as.list(params), envir = globalenv())

  currt <- 0
  tout <- currt
  petermat <- listmodel$petermatrix
  totaltransitions <- 0
  currx0 <- x0
  xout <- matrix(currx0, nrow = 1, ncol = length(currx0))

  list2env(as.list(currx0), envir = globalenv())

  currprocessrates <- sapply(
    strprocesses,
    function(expr) eval(parse(text = expr))
  )
  print("run")
  totalprocessrate <- sum(currprocessrates)
  continuemodel <- totalprocessrate > 0
  while (continuemodel) {
    print(totaltransitions)
    totaltransitions <- totaltransitions + 1
    # weighted sample process
    processidx <- sample(seq_along(currprocessrates), 1,
      prob = currprocessrates
    )
    currpetercol <- petermat[, processidx]
    currx0 <- currx0 + currpetercol
    list2env(as.list(currx0), envir = globalenv())
    xout <- rbind(xout, matrix(currx0, nrow = 1, ncol = length(currx0)))
    # update time
    currt <- currt + stats::rexp(1, rate = totalprocessrate)
    tout <- c(tout, currt)
    # update rates
    currprocessrates <- sapply(
      strprocesses,
      function(expr) eval(parse(text = expr))
    )
    totalprocessrate <- sum(currprocessrates)
    continuemodel <- (totalprocessrate > 0) && (currt < maxt)
  }
  return(list(t = tout, x = xout))
}
